"""update constraints

Revision ID: 3f3d1394abc5
Revises: 40e010769d5e
Create Date: 2021-09-12 12:04:04.830228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3d1394abc5'
down_revision = '40e010769d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_todo_list_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'todo_lists', ['todo_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_todo_list_id_fkey', 'tasks', 'todo_lists', ['todo_list_id'], ['id'])
    # ### end Alembic commands ###
