"""Added users table

Revision ID: 985ae15b1848
Revises: 
Create Date: 2021-07-25 20:57:11.599018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = '985ae15b1848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.execute(
        CreateSequence(sa.Sequence('user_id_seq'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute(
        DropSequence(sa.Sequence('user_id_seq'))
    )
    # ### end Alembic commands ###
