"""Added auth key table

Revision ID: a9dbb9f296a7
Revises: 985ae15b1848
Create Date: 2021-07-25 21:49:35.023314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dbb9f296a7'
down_revision = '985ae15b1848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_key_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_key_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_keys')
    # ### end Alembic commands ###
