"""Added todo list table

Revision ID: c5098df6bfbf
Revises: a9dbb9f296a7
Create Date: 2021-07-25 23:27:26.606096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = 'c5098df6bfbf'
down_revision = 'a9dbb9f296a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        CreateSequence(sa.Sequence('todo_list_id_seq'))
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_lists')
    op.execute(
        DropSequence(sa.Sequence('todo_list_id_seq'))
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###
