name: ToDo List backend tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todolist
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      PG_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/todolist
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: PWD backend
        run: pwd
        working-directory: backend/
      - name: LS backend
        run: ls
        working-directory: backend/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: backend/
      - name: Lint with flake8
        run: flake8 .
        working-directory: backend/
      - name: Type checking
        run: mypy .
        working-directory: backend/
      - name: Apply Migrations
        run: alembic upgrade head
        working-directory: backend/
